延迟执行指的是命令等到结果真正需要的时候执行

## 获取结果
当用到所需要的变量时，进行计算，获取结果

In [3]:
from mxnet import nd
from time import time
start = time()
x = nd.random_uniform(shape=(2000,2000))
y = nd.dot(x,x)
print('workloads are queued:\t%f sec' % (time() - start))
print(y)
print('workloads are finished:\t%f sec' % (time() - start))

workloads are queued:	0.120090 sec

[[501.1584  508.2972  495.65228 ... 492.847   492.69086 490.04803]
 [508.81046 507.18216 495.17426 ... 503.10532 497.2931  493.6792 ]
 [489.566   499.47006 490.17715 ... 490.99936 488.05008 483.28833]
 ...
 [484.00186 495.7179  479.92142 ... 493.69955 478.89185 487.2074 ]
 [499.64926 507.651   497.5939  ... 493.0475  500.74518 495.82706]
 [516.0143  519.17145 506.35403 ... 510.08875 496.35614 495.42523]]
<NDArray 2000x2000 @cpu(0)>
workloads are finished:	0.618548 sec


## 立即获得结果
以下还有其余方法获取结果

In [4]:
start = time()
y = nd.dot(x, x)
y.wait_to_read()
time() - start

0.21516847610473633

In [5]:
start = time()
y = nd.dot(x, x)
nd.waitall()#等待所有的延迟执行执行完成
time() - start

0.2176804542541504

任何方法从NDArray搬运到其他不支持延迟执行的数据结构里都会触发等待，例如asnumpy(), asscalar()

In [6]:
start = time()
y = nd.dot(x, x)
y.asnumpy()
time() - start

0.29424619674682617

In [7]:
start = time()
y = nd.dot(x, x)
y.norm().asscalar()
time() - start

0.32567429542541504