In [6]:
from mxnet import nd
def pure_batch_norm(X,gamma,beta,eps = 1e-5):
    assert len(X.shape) in (2,4)
    if len(X.shape) == 2:
        mean = X.mean(axis = 0)
        variance = ((X - mean)**2).mean(axis = 0)
    if len(X.shape) == 4:
        #对于每个通道算均值和方差，切保持4D形状
        #2D卷积： batch_size x channel x height x width
        mean = X.mean(axis = (0,2,3),keepdims = True)
        variance = ((X - mean)**2).mean(axis=(0,2,3),keepdims = True)
    X_hat = (X - mean) / nd.sqrt(variance + eps)
    return gamma.reshape(mean.shape) * X_hat + beta.reshape(mean.shape)

In [3]:
A = nd.arange(6).reshape((3,2))
A


[[0. 1.]
 [2. 3.]
 [4. 5.]]
<NDArray 3x2 @cpu(0)>

In [7]:
pure_batch_norm(A, gamma= nd.array([1,1]), beta = nd.array([0,0]))


[[-1.2247427 -1.2247427]
 [ 0.         0.       ]
 [ 1.2247427  1.2247427]]
<NDArray 3x2 @cpu(0)>

In [8]:
B = nd.arange(18).reshape((1,2,3,3))
B


[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)>

In [9]:
pure_batch_norm(B, gamma=nd.array([1,1]), beta=nd.array([0,0]))


[[[[-1.5491922  -1.1618942  -0.7745961 ]
   [-0.38729805  0.          0.38729805]
   [ 0.7745961   1.1618942   1.5491922 ]]

  [[-1.5491922  -1.1618942  -0.7745961 ]
   [-0.38729805  0.          0.38729805]
   [ 0.7745961   1.1618942   1.5491922 ]]]]
<NDArray 1x2x3x3 @cpu(0)>